// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestBrandsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testBrands() {
    driver.get("https://www.staples.ca/");
    driver.manage().window().setSize(new Dimension(1324, 807));
    driver.findElement(By.id("accessible-megamenu-nav-item-Brands")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".accessible-megamenu-panel-group-columns:nth-child(2) > li:nth-child(1) .article-link-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".accessible-megamenu-panel-group-columns:nth-child(2) > li:nth-child(1) .article-link__cta"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.findElement(By.cssSelector(".accessible-megamenu-panel-group-columns:nth-child(2) > li:nth-child(1) .article-link__cta")).getText(), is("Shop Now"));
    assertThat(driver.findElement(By.cssSelector(".accessible-megamenu-panel-group-columns:nth-child(2) > li:nth-child(1) .article-link__title")).getText(), is("Apple"));
    driver.findElement(By.cssSelector(".accessible-megamenu-panel-group-columns:nth-child(2) > li:nth-child(1) .article-link__title")).click();
    assertThat(driver.findElement(By.cssSelector(".my-5 > .col-6:nth-child(2) .d-table")).getText(), is("Shop Now"));
    driver.findElement(By.cssSelector(".my-5 > .col-6:nth-child(2) .d-table")).click();
    driver.findElement(By.linkText("Apple MacBook Pro 13\" Notebook, Apple M1 Chip, 256 GB SSD, 8 GB Unified Memory, Space Grey")).click();
    driver.findElement(By.cssSelector(".d-none .product-title")).click();
    assertThat(driver.findElement(By.cssSelector(".d-none #\\34 807456227457")).getText(), is("Apple MacBook Pro 13\\\" Notebook, Apple M1 Chip, 256 GB SSD, 8 GB Unified Memory, Space Grey"));
  }
}
