// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestSearchFunctionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testSearchFunction() {
    driver.get("https://www.staples.ca/");
    driver.manage().window().setSize(new Dimension(1324, 807));
    driver.findElement(By.id("algoliasearch-searchbar-input")).click();
    driver.findElement(By.id("body-staples-ca-the-working-and-learning-company-work-learn-grow")).click();
    driver.findElement(By.id("algoliasearch-searchbar-input")).click();
    driver.findElement(By.id("react-autowhatever-1-section-0-item-0")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".searchbar-input-container > .clear-button"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".searchbar-input-container > .clear-button")).getText(), is("CLEAR"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".search-button-text"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".search-button-text")).getText(), is("SEARCH"));
    driver.findElement(By.cssSelector(".ais-block")).click();
    assertThat(driver.findElement(By.cssSelector(".seo-search-query")).getText(), is("SAMSUNG TABLET"));
  }
}
