// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestDealsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testDeals() {
    driver.get("https://www.staples.ca/");
    driver.manage().window().setSize(new Dimension(1324, 807));
    js.executeScript("window.scrollTo(0,65.5999984741211)");
    driver.findElement(By.id("accessible-megamenu-nav-item-Deals")).click();
    driver.findElement(By.cssSelector("picture > img:nth-child(2)")).click();
    js.executeScript("window.scrollTo(0,61.599998474121094)");
    assertThat(driver.findElement(By.cssSelector(".mt-4:nth-child(1) .btn")).getText(), is("SHOP NOW"));
    driver.findElement(By.cssSelector(".mt-4:nth-child(2) .btn")).click();
    js.executeScript("window.scrollTo(0,8.800000190734863)");
    driver.findElement(By.cssSelector(".ais-hits--item:nth-child(2) .top-product")).click();
    assertThat(driver.findElement(By.cssSelector(".ais-hits--item:nth-child(2) strike")).getText(), is("$99.99"));
    {
      WebElement element = driver.findElement(By.cssSelector(".ais-hits--item:nth-child(2) .money"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ais-hits--item:nth-child(2) .money"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ais-hits--item:nth-child(2) .money"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".ais-hits--item:nth-child(2) .money")).click();
    driver.findElement(By.cssSelector(".ais-hits--item:nth-child(2) .money")).click();
    assertThat(driver.findElement(By.cssSelector(".ais-hits--item:nth-child(2) .money")).getText(), is("$50.00"));
  }
}
