// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestStoreNearbyMeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testStoreNearbyMe() {
    driver.get("https://www.staples.ca/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.linkText("1215 9 Avenue Southwest")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#store-locator-header .store-locator-modal__col > .button"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#store-locator-header .search-text"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#store-locator-header .store-locator-modal__col > .button")).getText(), is("STORE FINDER"));
    driver.findElement(By.cssSelector("#store-locator-header .store-locator-modal__col > .button")).click();
    driver.findElement(By.cssSelector(".leaflet-marker-icon:nth-child(1)")).click();
    driver.findElement(By.linkText("My Store")).click();
    driver.findElement(By.linkText("Make My Store")).click();
    driver.findElement(By.cssSelector(".leaflet-marker-icon:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector(".add-text:nth-child(2)")).getText(), is("1215 9 Avenue Southwest"));
  }
}
