// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testLogin() {
    driver.get("https://www.staples.ca/");
    driver.manage().window().setSize(new Dimension(1248, 777));
    {
      WebElement element = driver.findElement(By.cssSelector(".cart-counter__icon--desktop"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".header__link-account > .header__icon--desktop"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".header__link-account > .header__icon--desktop")).click();
    driver.findElement(By.id("customer_email")).click();
    driver.findElement(By.id("customer_email")).sendKeys("mapatel5169@gmail.com");
    driver.findElement(By.id("customer_password")).click();
    driver.findElement(By.id("customer_password")).sendKeys("Abcd@1234");
    assertFalse(driver.findElement(By.cssSelector(".jss4")).isSelected());
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".button--button"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".button--button")).getText(), is("SIGN IN"));
    driver.findElement(By.cssSelector(".button--button")).click();
  }
}
