// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestCartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testCart() {
    driver.get("https://www.staples.ca/");
    driver.manage().window().setSize(new Dimension(1324, 807));
    {
      WebElement element = driver.findElement(By.cssSelector(".submit-button-desktop > .justify-self-end"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,373.6000061035156)");
    driver.findElement(By.id("accessible-megamenu-nav-item-Shop")).click();
    js.executeScript("window.scrollTo(0,153.1999969482422)");
    driver.findElement(By.cssSelector(".shop-tab__link:nth-child(6) div")).click();
    {
      WebElement element = driver.findElement(By.linkText("Chromebooks"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".accessible-megamenu-panel-group--shop-content__column:nth-child(3) li:nth-child(3) .megamenu-category-item__image")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".ais-hits--item:nth-child(1) .button"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".ais-hits--item:nth-child(1) .button")).getText(), is("ADD TO CART"));
    driver.findElement(By.cssSelector(".ais-hits--item:nth-child(1) .button")).click();
    driver.findElement(By.cssSelector(".modal-cart-ctas__view-cart")).click();
    driver.findElement(By.cssSelector(".row:nth-child(1) > .col-8 .row:nth-child(2) .Checkbox__Element")).click();
    driver.findElement(By.cssSelector(".row:nth-child(3) > .col-7 .Checkbox__Element")).click();
    driver.findElement(By.cssSelector(".row:nth-child(4) .Checkbox__Element")).click();
    driver.findElement(By.cssSelector(".row:nth-child(2) .row:nth-child(2) .Checkbox__Element")).click();
    driver.findElement(By.cssSelector(".row:nth-child(2) .cart__item-remove > .d-block:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.linkText("Remove Item"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Remove Item")).click();
  }
}
